export const ambassadorArray = [
  {
    id: '1',
    ambassador:
      'Константин Константинопольский Константинопольский Константинопольский Константинопольский',
    Status: 'active',
    promo: '444',
    telegram: 'alter',
    program: 'Фронт',
    date_receipt: '01.02.2022',
    gender: 'woman',
    address: 'Москва, ул. Пушкина, д. 17',
    activity: 'Вести блог',
    e_mail: '12345@ya.ru',
  },

  {
    id: '2',
    ambassador: 'Амбассадор',
    Status: 'active',
    promo: '44334',
    telegram: 'front',
    program: 'Фронт',
    date_receipt: '02.02.2022',
    gender: 'man',
    address:
      'РФ, Новосибирская область, Бердск, Территория, изъятая из земель подсобного хозяйства Всесоюзного центрального совета профессиональных союзов для организации крестьянского хозяйства, дом 17',
  },

  {
    id: '3',
    ambassador: 'Амба22ссадор',
    Status: 'pending',
    promo: '444',
    telegram: 'moskow',
    program: 'Фронт',
    date_receipt: '03.02.2022',
    gender: 'man',
    address: 'Москва, ул. Пушкина, д. 17',
  },
  {
    id: '4',
    ambassador: 'Амбассадор',
    Status: 'candidate',
    tel: '343234234',
    promo: '444',
    telegram: 'moskow',
    email: 'test@test',
    date_receipt: '01.02.2022',
    gender: 'woman',
    program: 'Фронт',
  },
  {
    id: '5',
    ambassador: 'Амбассадор',
    Status: 'pending',
    tel: '343234234',
    promo: '444',
    telegram: 'mosk888ow',
    email: 'test@test',
    date_receipt: '02.02.2022',
    gender: 'man',
    program: 'Бэк',
  },

  {
    id: '6',
    ambassador: 'Амбассадор',
    Status: 'candidate',
    tel: '343234234',
    promo: '444',
    telegram: 'mos4444kow',
    email: 'test@test',
    date_receipt: '03.02.2022',
    gender: 'man',
    program: 'Бэк',
  },
  {
    id: '7',
    ambassador: 'Архив Амбассадор',
    Status: 'deleted',
    tel: '343234234',
    promo: '444',
    telegram: 'moskow',
    email: 'test@test',
    date_receipt: '01.02.2022',
    gender: 'woman',
    program: 'Фронт',
  },
  {
    id: '8',
    ambassador: 'Амбассадор',
    Status: 'deleted',
    tel: '343234234',
    promo: '444',
    telegram: 'mosk888ow',
    email: 'test@test',
    date_receipt: '02.02.2022',
    gender: 'man',
    program: 'Бэк',
  },
];
